import subprocess
print("Installing required packages...")
subprocess.check_output(['conda','install','--yes','--file','requirements.txt'])
print("Installed requirements")
print("Installing openbabel...")
subprocess.check_output(['conda','install','--yes','-c','openbabel', 'openbabel'])
print("Installed openbabel")
print("Installing beautifulsoup4...")
subprocess.check_output(['conda','install','--yes','-c','anaconda', 'beautifulsoup4'])
print("Installed beautifulsoup4")
print("Installing requests...")
subprocess.check_output(['conda','install','--yes','-c','anaconda', 'requests'])
print("Finished install all packages")